version: '{branch}-{build}'
cache:
  - C:\projects\qutebrowser\.cache
build: off
environment:
    PYTHONUNBUFFERED: 1
    matrix:
    - TESTENV: py34
    - TESTENV: unittests-frozen
    - TESTENV: pylint

install:
  - C:\Python27\python -u scripts\dev\ci_install.py

test_script:
  - C:\Python34\Scripts\tox -e %TESTENV% -- -p "no:sugar" -v --junitxml=junit.xml

after_test:
  - ps: |
      if ($env:TESTENV -ne "pylint") {
          $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
          $file = '.\junit.xml'
          (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))
      }
      if ($env:TESTENV -eq 'py34') {
          C:\Python34\Scripts\codecov -e TESTENV -X gcov
      }
